### ISSUE TITLE
FPS drops when using fishing rod

### ISSUE THREAD

**Issue by ghost** [Nettakrim/Fishing-Ruler#1]
When I'm using fishing rod fps drops to 0 and it's impossibe to do anything till I will drop fishing rod or switch slot. I'm on 1.19.3 Fabric loader 0.14.18

**Comment by Nettakrim** [comment]
huh, it works fine for me on 1.19.3 (admittedly on fabric 0.14.14)

are you using any other mods etc?

im not too sure what could even be causing issues, (unlike with my spyglass mod where im pretty sure i know where any bottlenecks are), the only places problems could arise is if something was messing with the action bar or the bobber entity

**Comment by ghost** [comment]
Yes, I'm playing in my modpack: https://www.curseforge.com/minecraft/modpacks/minecraftory
I'm not actually sure about why this can happen, but if you talking about bossbars, there I have resourcepack that makes bossbars for bosses more beautiful, Enhanced Bossbars

**Comment by Nettakrim** [comment]
wow just downloaded the modpack, i see what you mean that is very bad fps

the action bar is the text that can appear above your hotbar (eg when holding an item it says its name)

it does appear that there is another mod doing something with action bars, as placing a repeating command block with the command `/title @p actionbar "hi!"` crashed my game

disabling all resource packs doesnt fix it so its definitely an incompatibility with another mod

**Comment by ghost** [comment]
Oh, OK, I have an idea what can be causing this. I need to test it

**Comment by Nettakrim** [comment]
im currently just disabling half the mods at a time to binary search what the issue is :P

**Comment by Nettakrim** [comment]
ok the issue is with `GoogleChat`, and its on their end (since they translate every message, whenever a message is sent it lags, and that includes the action bar - however the action bar doesnt even end up getting translated)

**Comment by Nettakrim** [comment]
the easiest solution would obviously be to either remove GoogleChat or Fishing Ruler, or to submit an issue to googlechat about the fact that action bars A) dont get translated, and B) crash the game when using a repeating command block (regular /say might as well) - however to fix the lag completely, GoogleChat *would* need some sort of multithreading system, which is complicated

**Comment by ghost** [comment]
I'll write an issue for developer of GoogleChat. When he will fix that I'll add your mod to modpack if you don't mind. Or I will remove GoogleChat, it higly depends on MCChatGPT mod for which google chat was put because sometimes it refuses to speak other languages

**Comment by ghost** [comment]
Thank you very much for help!
