### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by pizzav-xyz** [Nettakrim/Fishing-Ruler#2]
psl port to 1.20.2

**Comment by Nettakrim** [comment]
does the 1.20 version not work in .2? I just assumed it would lol

**Comment by pizzav-xyz** [comment]
> does the 1.20 version not work in .2? I just assumed it would lol

can you put the 1.20.2 version on modrinth

**Comment by Nettakrim** [comment]
modrinth updated, can you test it works :P

**Comment by pizzav-xyz** [comment]
> modrinth updated, can you test it works :P

it wroks

**Comment by Nettakrim** [comment]
cool!
