### ISSUE TITLE
[ADDITION REQUEST] | 1.19.3 | Fishing Ruler

### ISSUE THREAD

**Issue by ExiledLizard** [Nettakrim/Fishing-Ruler#3]
Hey, @Nettakrim , I have an idea, that adds something to your mod "Fishing Ruler" - A display that shows you what you caught. So, when you catch a fish/item, the ruler will be interrupted for **1** second, and it will show what item you just caught (format: "Caught: -caughtItem-"). Could you implement this for the **1.19.3** build of the mod?

**Comment by Nettakrim** [comment]
ooh that is interesting and also fishing ruler is the easiest of my mods for me to backport so i can definately do that, although i am quite busy atm so expect to wait a while

ofc all enchanted books are called "Enchanted Book" so id assume id want an edge case where it can display thoss differently (i would probably also make it a different color for fish vs treasure)

**Comment by Nettakrim** [comment]
this will be done for the latest versions, ill make a seperate issue for backports
