### ISSUE TITLE
backports

### ISSUE THREAD

**Issue by Nettakrim** [Nettakrim/Fishing-Ruler#4]
as per #3

**Comment by ExiledLizard** [comment]
Its been a while... When do you think you can implement the caught-item display for the 1.19.x versions of **Fishing Ruler**, @Nettakrim?

**Comment by Nettakrim** [comment]
ah i forgot about this lol, ill probably do it soon

**Comment by ExiledLizard** [comment]
No worries! Ok!

**Comment by Nettakrim** [comment]
here you go
https://modrinth.com/mod/fishing-ruler/version/1.0.5-mc1.19.X

**Comment by ExiledLizard** [comment]
@Nettakrim, thank you!

**Comment by ExiledLizard** [comment]
I just tested it out, and it works **GREAT** - thank you again!
